# Generated by Django 5.2.14 on 2026-06-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_program_id_alter_programfeature_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
    ]
