# Generated by Django 5.2.14 on 2026-06-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_program_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(
                upload_to='programs/',
                blank=True,
                null=True
            ),
        ),
    ]